server:
  port: 8003

spring:
  #项目名称
  application:
    name: service-vod

  #Nacos服务器连接
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  #开发环境
  profiles:
    active: dev
  #上传文件大小限制
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  # 数据库设置

#阿里云 OSS
  #不同的服务器，地址不同
#  aliyun.oss.file.endpoint=your endpoint
#  aliyun.oss.file.keyid=your accessKeyId
#  aliyun.oss.file.keysecret=your accessKeySecret
#  #bucket可以在控制台创建，也可以使用java代码创建
#  aliyun.oss.file.bucketname=guli-file
aliyun:
  oss:
    file:
      endpoint: oss-cn-beijing.aliyuncs.com
      keyid: LTAI5tN1hcuVmn1zczKRScTb
      keysecret: 0AuXUHKZMUxSFtitC54IiQgM2WhoZx
      bucketname: yantao-zhang



