server:
  port: 8222

spring:
  #项目名称
  application:
    name: service-gateway

  #Nacos服务器连接
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
#      使服务发现路由
      discovery:
        locator:
          enabled: true
      routes:
        # 随便写唯一的
        - id: service-acl
                #  设置路由的路径  lb：//nacos注册的名称
          uri: lb://service-acl
                 #  设置路由的断言  代理的路径
          predicates:
            - Path=/*/acl/** # 路径匹配
        - id: service-edu
          uri: lb://service-edu
          predicates:
            - Path=/eduservice/** # 路径匹配

        - id: service-ucenter
          uri: lb://service-ucenter
          predicates:
            - Path=/ucenter/** # 路径匹配


